### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by feitiandemiaomi** [wenxichen/tensorflow_yolo2#2]
Thanks your great repo, It is very useful ,I would like to train from the scratch without pretrained weights, but I found nothing the result of detecting , so , Whether I must use the pretained weights for initialization ,looking forward to your reply ,Thanks

**Comment by wenxichen** [comment]
Hi,

Sorry that I have not been maintaining this repo as frequent as I would like, because some other stuff that keep me busy. I have just updated the training description for the darknet19 on Pascal. So the training is two stages: First, you train the darknet19 on imagenet for classification. Then, you use the saved ckpts to train on Pascal for detection. Let me know how it goes!

Best,
Wenxi
